spring.datasource.url=jdbc:postgresql://localhost:5433/document_schema
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


#access_key=Ii3vSQ0sZrM7nZeVjGwV
#secret_key=ywzG4bcabqgt0UzKjCeKwUtXcpH0WHFYi7Ocis4u
minio.url=http://localhost:9000
minio.access-key=Ii3vSQ0sZrM7nZeVjGwV
minio.secret-key=ywzG4bcabqgt0UzKjCeKwUtXcpH0WHFYi7Ocis4u
minio.bucket-name=document-bucket